name: moodle_project

services:
  moodle:
    image: bitnami/moodle:5.0.2
    container_name: moodle502
    ports:
      - "9090:8080"  
      - "9443:8443"  
    environment:
      - MOODLE_DATABASE_TYPE=mysqli
      - MOODLE_DATABASE_HOST=mysql
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=moodle
      - MOODLE_DATABASE_PASSWORD=moodle_pass
      - MOODLE_DATABASE_NAME=moodle
    volumes:
      - moodle_data:/bitnami/moodle

  mysql:
    image: mysql:8.4
    container_name: mysql8.4
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=moodle
      - MYSQL_USER=moodle
      - MYSQL_PASSWORD=moodle_pass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  moodle_data:
  mysql_data:
