server:
  port: 8084

spring:
  application:
    name: courseservice
  data:
    mongodb:
      uri: mongodb+srv://lockbkbang:lHkgnWyAGVSi3CrQ@cluster0.z20xcvv.mongodb.net/courseservice?retryWrites=true&w=majority&appName=Cluster0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka