name: CI/CD course-service-py

on:
  push:
    paths:
      - 'courseservice_py/**'
  pull_request:
    paths:
      - 'courseservice_py/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          cd courseservice_py
          docker build -t ${{ secrets.DOCKER_USERNAME }}/courseservice_py:latest .

      # Push image lên DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/courseservice_py:latest

      # Optional: Deploy (tuỳ môi trường)
      - name: Deploy service
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/courseservice_py:latest
            docker stop courseservice_py || true
            docker rm courseservice_py || true
            docker run -d \
                --name course_service \
                --network app-network \
                -p 5001:5001 \
                -e MONGO_URI="${{ secrets.MONGO_URI }}" \
                -e MOODLE_API_BASE="${{ secrets.MOODLE_API_BASE }}" \
                -e MOODLE_TOKEN="${{ secrets.MOODLE_TOKEN }}" \
                --name courseservice_py \
                ${{ secrets.DOCKER_USERNAME }}/courseservice_py:latest