name: CI/CD recommend-service

on:
  push:
    paths:
      - 'recommend-service/**'
  pull_request:
    paths:
      - 'recommend-service/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          cd recommend-service
          docker build -t ${{ secrets.DOCKER_USERNAME }}/recommend_service:latest .

      # Push image lÃªn DockerHub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/recommend_service:latest

      # Deploy service (qua SSH)
      - name: Deploy recommend service
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/adaptive-learning/moodle-adaptive-learning-plugin 
            docker compose --env-file .env.production -f docker-compose.prod.yml pull recommend-service
            docker compose --env-file .env.production -f docker-compose.prod.yml up -d recommend-service  